admin-mypage
colomai/portfolio pull request #25
Opened 2024-12-27 09:50 UTC by colomai

管理者マイページ、編集ページ、機能を作成して、従業員の時と同じ表示がされています
そして、従業員マイページの時と同じようにプロフィール画像(imageカラム)のアップロードは後の工程でやる予定になったので、このブランチではページの作成までをしています

2024-12-27 14:00 UTC, yuki-tachi0219 commented on app/views/admins/edit.html.erb
> +<div class="container text-center">
`app/views/employees/edit.html.erb`と同じなので、共通化しましょう。
このファイルの内容を全く同じ内容を書いたファイルを作り、それしかるべき場所に置き、renderを使って呼び出しましょう。コントローラで定義した`@user`を使っているので、値の受け渡しをする必要がありますね。

うまくできれば、このファイルは、
```
render '〇〇/〇〇/〇〇, resource: 〇〇'
```
みたいな書き方で1行で表現できます。`app/views/employees/edit.html.erb`も同様、1行で表現できます。
必ずしも`resource`という変数にしなくてもいいですね。好きに決めてください。

同じことをshow.html.erbでも実施してください

2024-12-27 14:01 UTC, yuki-tachi0219 requested changes

2024-12-27 14:01 UTC, yuki-tachi0219 commented on app/controllers/admins_controller.rb
> +  end
def~endのかたまりの間に空行を入れてください

2025-01-09 04:21 UTC, colomai commented on app/views/admins/edit.html.erb
> +<div class="container text-center">
修正して画像も以前と同じく問題なく表示されています
b3741b4bb9c63b3ddb0ce48fea39a4ee8177767e

2025-01-09 04:21 UTC, colomai commented on app/controllers/admins_controller.rb
> +  end
修正しました
b3741b4bb9c63b3ddb0ce48fea39a4ee8177767e

2025-01-09 05:56 UTC, yuki-tachi0219 commented on app/views/shared/_edit_form.html.erb
> +  <%= render 'shared/error_messages', resource: resource %> <%# 変数名をresourceに変更 %>
コメントに書かれている内容は実装し終えましたか？終えたならコメント削除で

2025-01-09 05:57 UTC, yuki-tachi0219 commented on app/views/shared/_edit_form.html.erb
> +  <%= form_with(model: resource, url: url, method: :put, local: true) do |form| %> <%# url変数も追加 %>
コメントに書かれている内容は実装し終えましたか？終えたならコメント削除で

2025-01-09 08:08 UTC, colomai commented on app/views/shared/_edit_form.html.erb
> +  <%= form_with(model: resource, url: url, method: :put, local: true) do |form| %> <%# url変数も追加 %>
削除しました
2bed36f34999ec1a8a5c250dc79879c3c680aae7

2025-01-09 08:08 UTC, colomai commented on app/views/shared/_edit_form.html.erb
> +  <%= render 'shared/error_messages', resource: resource %> <%# 変数名をresourceに変更 %>
削除しました
2bed36f34999ec1a8a5c250dc79879c3c680aae7

2025-01-09 08:16 UTC, yuki-tachi0219 approved these changes
LGTM!

2025-01-09 10:01 UTC, merged